import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const styles = read('assets/styles/styles.css');
const panels = read('assets/scripts/node-panels.js');
const sectionPanels = read('assets/scripts/section-panels.js');
const orientationRecovery = read('assets/scripts/orientation-recovery.js');

assert(!html.includes('look-around.js'), 'homepage must not load a stage gesture handler');
assert(/#stage\s*{[\s\S]*?touch-action:\s*none/.test(styles), 'stage must reject browser gestures');
assert(!/is-gesturing|is-recentring/.test(styles), 'gesture-only stage states must stay removed');
assert(/@media \(pointer: coarse\)[\s\S]*?#backgroundRings\s*{[\s\S]*?1388px/.test(styles),
  'phone must retain the measured desktop ring field');
assert(/@media \(pointer: coarse\)[\s\S]*?#ringTitle\s*{[\s\S]*?1388px/.test(styles),
  'phone must retain the desktop-sized wordmark field');
assert(/@media \(pointer: coarse\)[\s\S]*?#radialMenu\s*{[\s\S]*?width:\s*400px/.test(styles),
  'phone must retain the desktop wheel size');
assert(/el\.addEventListener\('pointerdown', \(e\) => startDrag\(node, e\)\)/.test(panels),
  'title and welcome panels must remain draggable');
assert(/const move = \(e\) => place\([\s\S]*?!COARSE_POINTER/.test(panels),
  'touch dragging must track the finger without desktop grid snapping');
assert(/\.node-panel\.is-dragging\s*{[\s\S]*?box-shadow:/.test(styles),
  'touching a draggable panel must provide a prominent visual response');
assert(!panels.includes('document.fonts.ready'),
  'late font loading must not re-home the panels');
const panelSizeObserver = panels.match(/const sizeObserver = new ResizeObserver\([\s\S]*?for \(const node of nodes\) if \(node\.resizes\)/)?.[0] || '';
assert(panelSizeObserver && !/\bplace\(/.test(panelSizeObserver),
  'panel content resizing must update measurements without moving the panel');
assert(/const HOLD_MS = 500/.test(sectionPanels),
  'holding a touch sector must have a deliberate activation delay');
assert(/suppressHeldClick === link[\s\S]*?event\.preventDefault/.test(sectionPanels),
  'only the compatibility click generated by a completed hold may be swallowed');
assert(!sectionPanels.includes('Touch two-step'),
  'a normal touch tap must not be converted into preview-first navigation');
assert(/@media \(pointer: coarse\)[\s\S]*?\.section-panel\s*{[\s\S]*?width:\s*min\(320px, 82vw\)/.test(styles),
  'touch preview panels must use the compact phone dimensions');
assert(html.includes('assets/scripts/orientation-recovery.js'),
  'homepage must load the external orientation recovery under the script CSP');
assert(/innerWidth > layoutWidth \* 1\.25/.test(orientationRecovery)
  && /visualScale < 0\.8/.test(orientationRecovery),
  'orientation recovery must require both the retained-width and browser-scale defects');

console.log('  static-homepage: ok (fixed crop, direct panel dragging, tap navigation, hold previews)');
